#%RAML 1.0 Library
types:
  Conditional:
    type: object
    properties:
      if?:

  WithUri:
    type: object
    properties:
      uri:

  WithSource:
    type: object
    properties:
      source:

annotationTypes:
  deny: [Conditional | nil]
  remove: [Conditional | nil]
  rewrite: [WithUri, Conditional]
  set: [WithSource, Conditional]
